# Generated by Django 5.1.6 on 2025-04-17 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('origin_x', models.FloatField()),
                ('origin_y', models.FloatField()),
                ('destination_x', models.FloatField()),
                ('destination_y', models.FloatField()),
                ('bearing', models.FloatField()),
                ('payment', models.IntegerField()),
                ('initial_amount', models.IntegerField(default=1000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
