# Generated by Django 5.1.7 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdirection",
            name="destination_x",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userdirection",
            name="destination_y",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userdirection",
            name="origin_x",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userdirection",
            name="origin_y",
            field=models.CharField(max_length=50),
        ),
    ]
